name: Lint Workflows

on:
  workflow_call:

permissions:
  contents: read

jobs:
  actionlint:
    name: Run actionlint
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v7

      - name: Download actionlint
        id: get_actionlint
        run: bash <(curl https://raw.githubusercontent.com/rhysd/actionlint/main/scripts/download-actionlint.bash)
        shell: bash

      - name: Run actionlint
        run: ${{ steps.get_actionlint.outputs.executable }} -color
        shell: bash
