name: Deprecate version of package from npm

on:
  workflow_dispatch:
    inputs:
      VERSION:
        description: 'Version to deprecate'
        required: true
      MESSAGE:
        description: 'Deprecation message'
        required: false
        default: 'This version is deprecated, please use the latest stable version'

env:
  LIBRARY_NAME: react-mindee-js

jobs:
  deprecate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: pnpm
          registry-url: https://registry.npmjs.org
      - name: Deprecate version
        run: pnpm deprecate "${LIBRARY_NAME}@${VERSION}" "${MESSAGE}"
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          VERSION: ${{ inputs.VERSION }}
          MESSAGE: ${{ inputs.MESSAGE }}
